CREATE DATABASE Essence;
CREATE TABLE Users (
    email CHAR(255) PRIMARY KEY,
    name CHAR(30) NOT NULL,
    password CHAR(76) NOT NULL,
    createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Google_Users (
    email CHAR(255) PRIMARY KEY,
    name CHAR(30) NOT NULL,
    createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);